### ISSUE TITLE
Cannot find module 'react-use-is-online' or its corresponding type declarations.

### ISSUE THREAD

**Issue by vladislavbogomolov** [cacheflow/react-use-is-online#11]
Cannot find module 'react-use-is-online' or its corresponding type declarations.

**Comment by cacheflow** [comment]
Thanks for notifying me of this. I’ll take a look.

**Comment by cachelina** [comment]
Hey! I think I solved the issue. It may have to do with the missing dist folder. I'll push up my suggestions.

**Comment by cacheflow** [comment]
Thanks for creating this issue @vladislavbogomolov. @cachelina PR seems to have fixed this, so I’m closing this issue.
